### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by mateuswetah** [IBICT/wp-govbr-tema#1]
Passos para a criação do tema. Este documento rastreia as atividades de desenvolvimento do tema e deve ser usado para referênciar algumas issues e discussões sobre o mesmo.

- [ ] [Configurar theme.json para espelhar o CSS do GovBR, visando garantir wysiwyg no editor de blocos #2](https://github.com/mateuswetah/govbr-tema/issues/2)
- [ ] [Limpar o máximo possível de CSS próprio do tema ou herdado do TwentyTwentyOne #3](https://github.com/mateuswetah/govbr-tema/issues/3)
- [ ] [Remover funções restantes do TwentyTwentyOne não utilizadas #4](https://github.com/mateuswetah/govbr-tema/issues/4)
- [ ] [Bloco de Collapse/Acordeão #6](https://github.com/mateuswetah/govbr-tema/issues/6)
- [ ] [Criar documentação para desenvolvedores, extraída automaticamente de comentários. #24](https://github.com/mateuswetah/govbr-tema/issues/24)
- [ ] [Estilizar rodapé usando block templates #5](https://github.com/mateuswetah/govbr-tema/issues/5)
- [ ] [Página de Configuração do tema para linkar documentação, listar plugins, configurações de Cookies, etc. #23](https://github.com/mateuswetah/govbr-tema/issues/23)
- [ ] [Traduzir comentários, documentação e algumas funções existentes para Português #16](https://github.com/mateuswetah/govbr-tema/issues/16)
- [ ] [Adicionar Skip Links para melhor acessibilidade #21](https://github.com/mateuswetah/govbr-tema/issues/21)
- [ ] Criar opção no Personalizar para usar layout padrão ou largo
- [ ] [Criar template para o header usando o componente do DS #8](https://github.com/mateuswetah/govbr-tema/issues/8)
    - [ ] [Criar menu usando um NavWalker #9](https://github.com/mateuswetah/govbr-tema/issues/9)
    - [ ] [Implementar modo de alto contraste #12](https://github.com/mateuswetah/govbr-tema/issues/12)
    - [ ] [Integração com o VLibras #13](https://github.com/mateuswetah/govbr-tema/issues/13)
    - [ ] [Criar painel para gerenciar cookies #25](https://github.com/mateuswetah/govbr-tema/issues/25)
    - [ ] Criar opção de mostrar botão de "Entrar"
        - [ ] SSO do Gov.br
        - [ ] [Login no WordPress #18](https://github.com/mateuswetah/govbr-tema/issues/18)
    - [ ] Criar opção de linguagem integrando com algum plugin (ver alternativas mais comuns e estilizar)
- [ ] [Criar função para renderizar Breadcrumb #10](https://github.com/mateuswetah/govbr-tema/issues/10)
- [ ] Criar [padrões de blocos](https://wordpress.org/patterns/about/):
    - [ ] Cartão com Ícone da FontAwesome
    - [ ] [Padrão de Bloco: Banner com Números #7](https://github.com/mateuswetah/govbr-tema/issues/7)
    - [ ] [Banner com cards claros #17](https://github.com/mateuswetah/govbr-tema/issues/17)
    - [ ] Banner com cards escuros
    - [ ] Cards e Lista de Posts, Grade com background-image... (customizar o bloco de loop) que serão usadas em Notícias Recentes. Talvez possa ser criado com uma [Variation do bloco](https://developer.wordpress.org/news/2022/12/building-a-book-review-grid-with-a-query-loop-block-variation/).
- [ ] Função ou plugin de botão de compartilhar - estilizar e criar opções... Isto é diferente de um botão com ícones de redes sociais, já que o de compartilhar abre nas redes ou faz uma função de enviar o link para a área de transferência.
- [ ] [Estilizar componente de paginação #14](https://github.com/mateuswetah/govbr-tema/issues/14)
- [ ] [Eleger e configurar plugin de ícones para FontAwesome #11](https://github.com/mateuswetah/govbr-tema/issues/11)
- [ ] Plugin de blocos de Carrossel
- [ ] Plugin de blocos de Banner com slide
- [ ] Plugin de bloco de Abas
- [ ] Plugin de bloco de Collapses
- [ ] [Criar actions (hooks) para inserção de conteúdo via código. #26](https://github.com/mateuswetah/govbr-tema/issues/26)
- [ ] [Estilo básico para archive #15](https://github.com/mateuswetah/govbr-tema/issues/15)
- [ ] Archive de resultado da busca com abas separadas por post type
- [ ] Criar post type Serviços e a Taxonomia associada a ele
- [ ] Templates diferentes de Página:
    - [ ] Página sem título (para home)
    - [ ] Criar Single diferente para Notícias (Posts) e Serviços. Este último tem uma barra lateral de widgets, além de um cabeçalho com ícone e a hierarquia de uma taxonomia ([Ver este exemplo](https://www.gov.br/pt-br/servicos/participar-de-atividades-educativas-e-obter-emprestimo-de-materiais-pedagogicos)).
- [ ] Criar estilos de blocos:
    - [ ] [Botão Terciário (e modificar o Outline para virar o Secundário) #19](https://github.com/mateuswetah/govbr-tema/issues/19)
    - [ ] [Botão Super chamativo verde (algumas páginas do gov.br tem isso para linkar para outros serviços) #20](https://github.com/mateuswetah/govbr-tema/issues/20)
- [ ] [Botão de voltar para o topo da página #22](https://github.com/mateuswetah/govbr-tema/issues/22)
- [ ] Integração [Tainacan](https://tainacan.org) (provalemnte um plugin)
    - [ ] Lista de Coleções
    - [ ] Lista de Itens da Coleção (pensar cabeçalho)
    - [ ] Lista de Itens do Termo (pensar cabeçalho)
    - [ ] Lista de Itens do Repositório
    - [ ] Página do Item
    - [ ] Opções de customizar no menu personalizar (copiar as existentes do Tainacan Interface)
